### ISSUE TITLE
docstring print in help with single command

### ISSUE THREAD

**Issue by fkgruber** [edornd/argdantic#45]
Hi
thanks for the useful tool. When we have a single command why not print the doctring of the function when we do --help?

Suppose I have
```
from argdantic import ArgParser

cli = ArgParser()


@cli.command()
def hello(name: str):
    """Print a greeting message."""
    print(f"Hello, {name}!")


if __name__ == "__main__":
    cli()
```

I would like to use it with
./test --name J

but when I do
./test --help 
I would like to see the documentation of hello:
Print a greeting message.

I rather not activate force_group because then I need to use it as

./test hello --name J
which is silly since there is only 1 command.

**Comment by edornd** [comment]
Hi @fkgruber, good catch! That's actually an easy fix, I never noticed it.

**Comment by fkgruber** [comment]
thanks!  Will it be available in pip?

**Comment by edornd** [comment]
Sorry if it took two geological eras, the small fix is now on PyPI!
