### ISSUE TITLE
Add support for python 3.12

### ISSUE THREAD

**Issue by edornd** [edornd/argdantic#49]
**Is your feature request related to a problem? Please describe.**
Previous fixes for typing fail, e.g. #44.

**Describe the solution you'd like**
Typing and imports should not break across versions, from 3.8 (or at least 3.10) to 3.12+.

**Describe alternatives you've considered**
Deprecate older versions of argdantic, or better, argdantic for older python versions.

**Additional resources**
- [how pydantic solves it](https://github.com/pydantic/pydantic/blob/b1bb24e8b7687e5891bce33f551625ac01b74b66/pydantic/v1/typing.py#L63)

**Comment by Andrew-Chen-Wang** [comment]
Hi wondering when Python 3.12 will be supported!

**Comment by edornd** [comment]
Hi @Andrew-Chen-Wang! Thank you for comment and interest, at the moment it was just a personal project, where I was the only maintainer, but by all means contributions are welcome.
Unfortunately I can't work on this as much as I'd like in this period, being a side project I have bigger priorities, but in the following weeks I should try and tackle this.
